### PR TITLE
Kernel 5.2 support

### PR DESCRIPTION
**Pull request by tak-fuji**
I deleted a compilation error for kernel 5.2.
In my situation, this change works well.

### CODE REVIEW

**Comment by matteogabburo** [comment]
I tried your commit and it doesn't work on my system (5.2.2-arch1-1-ARCH). It has a small code error (a not closed parenthesis) that gives a compilation error. I already did a pull request to your version of the code and now it should work.

**Comment by zebulon2** [comment]
> I tried your commit and it doesn't work on my system (5.2.2-arch1-1-ARCH). It has a small code error (a not closed parenthesis) that gives a compilation error. I already did a pull request to your version of the code and now it should work.

Thanks. Can you please do a pull request for my repository as well? Thank you very much in advance.

**Comment by zebulon2** [comment]
Another point: tak-fuji's patch is specific to 5.2, whereas yours to 5.2.2. Which version cut-off should be applied?

**Comment by matteogabburo** [comment]
Hi Zebulon! Yes, I'm making the pull request to you. I tested the corrected version of the patch of tak-fuji with my version of the kernel that is the 5.2.2 and it works, but I don't know if it also works with the 5.2.0 because I didn't test it personally (but with high probability yes).
