### ISSUE TITLE
Does not compile on 4.15 kernel

### ISSUE THREAD

**Issue by josetesan** [zebulon2/rtl8812au#10]
Hi, i was able to use this version with previous kernel 4.14.15, but after update to 4.15 ( and also got a 4.14.Z minor update ), was unable to recompile the module for current kernel.

```
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h:277:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h:278:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
In file included from /home/josetesan/tmp/rtl8812au/include/osdep_service.h:41:0,
                 from /home/josetesan/tmp/rtl8812au/include/drv_types.h:32,
                 from /home/josetesan/tmp/rtl8812au/core/rtw_ioctl_query.c:22:
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h: In function ‘_init_timer’:
In file included from /home/josetesan/tmp/rtl8812au/include/osdep_service.h:41:0,
                 from /home/josetesan/tmp/rtl8812au/include/drv_types.h:32,
                 from /home/josetesan/tmp/rtl8812au/core/rtw_ieee80211.c:25:
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h: In function ‘_init_timer’:
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h:277:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h:277:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h:278:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
/home/josetesan/tmp/rtl8812au/include/osdep_service_linux.h:278:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
```

Any idea how to help me build this ?
thanks a lot.

**Comment by josetesan** [comment]
I got the driver version from https://github.com/paspro/rtl8812au/, branch v5.1.5 and it does compile now.

**Comment by giupino82** [comment]
on Arch, reinstalling the aur package (from this branch) solved the issue.
the action downgrade the git version rtl8821au-dkms-git (5.1.5.r63.g06d399c-1 => 5.1.5.r57.g386f345-1)

**Comment by zebulon2** [comment]
It should be fine now, the branch is even with paspro's. However I recommend using the 5.2.20 repo.

**Comment by zebulon2** [comment]
It is now even with paspro's repository. Is it compiling fine?

**Comment by zebulon2** [comment]
It should be compiling for 4.15 now, closing this issue,
